### ISSUE TITLE
iGrill mini "Invalid device challenge"

### ISSUE THREAD

**Issue by TokTias** [kvantetore/igrill#8]
Hi !
I've got an iGrill Mini and I have tried with all keys found in the latest apk but I always end up with "Invalid device challenge" (I've set correct MAC address too of course) :

> Authenticating...
> encrypted device challenge: 954410c3d04a945fb4e986b4e18bb7cb
> decrypted device challenge: 1a8659a80d5d5a89ca3fc549efad0544
> Invalid device challenge
> Traceback (most recent call last):
>   File "monitor_igrill_v2.py", line 18, in <module>
>     periph = IGrillV2Peripheral(ADDRESS)
>   File "/home/pi/igrill-master/igrill.py", line 130, in __init__
>     IDevicePeripheral.__init__(self, address)
>   File "/home/pi/igrill-master/igrill.py", line 46, in __init__
>     raise RuntimeError("Unable to authenticate with device")
> RuntimeError: Unable to authenticate with device

Is there sopmething obvious that I am unable to see missing here for me to be able to connect ?

Cheers & TIA !
/Mathias

**Comment by Zeroexperiencelearner** [comment]
Who can hack an IG account for me, plz contact me.
